{
 "title": "IBM Runbook Automation",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "span_min",
    "label": "SLI Period",
    "query": "1 Hour : 60, 3 Hours : 180, 6 Hours : 360, 24 Hours : 1440,7 Days : 10080,30 Days : 43200"
   },
   {
    "name": "get_actions",
    "label": "Action",
    "query": {
     "query": "label_values(rba_action_execution_time,action_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "IBM RBA - Platform Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# IBM Runbook Automation\n\nEach minute the status of the runbook and automation service and connections RBA has configured are checked via the API (documented [here](https://www.ibm.com/docs/en/runbook-automation?topic=api-runbook-automation-documentation)). Each important API endpoint (\"status\", \"runbooks\", statistics\") status is checked for its availability. Current state (UP or DOWN) is detailed here. \n\nIn addition, status metrics are captured at the action and runbook level. To view open the \"Actions\" or \"Runbooks\" drop-down below.\n\nTo review SLI performance over time you should review the visualisations in the corresponding drop-down below.\n\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 }, "options": { "content": "# Current Platform Status" } },
  {
   "title": "Runbook Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sli_rba_service_status_runbook)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Automation Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sli_rba_service_status_automation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sli_rba_service_status_database)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sli_rba_api_status_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API - Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sli_rba_api_status_actions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API - Statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sli_rba_api_status_statistics)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API - Runbooks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sli_rba_api_status_runbooks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection - Script",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sli_rba_connection_status_script)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 }, "options": { "content": "# RBA Summary" } },
  {
   "title": "Runbook Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rba_runbook_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "description": "This is a count of production runbook executions and alert action runs",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 16 },
   "targets": [
    { "expr": "delta(rba_runbook_executions)", "legendFormat": "Production Runbook Executions" },
    {
     "expr": "sum(delta(rba_action_run_total))",
     "legendFormat": "Action Runs"
    }
   ]
  },
  {
   "title": "Action Status Breakdown - Total",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rba_action_run_cancelled_count)",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "sum(rba_action_run_failed_count)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rba_action_run_successful_count)",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rba_action_run_unknown_count)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(rba_action_run_unsuccessful_count)",
     "legendFormat": "Unsuccessful"
    }
   ]
  },
  {
   "title": "Action Run Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rba_action_run_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Action executions by status",
   "type": "timeseries",
   "description": "This is a count of action executions by status",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "sum(delta(rba_action_run_cancelled_count))",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "sum(delta(rba_action_run_failed_count))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(delta(rba_action_run_successful_count))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(delta(rba_action_run_unknown_count))",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(delta(rba_action_run_unsuccessful_count))",
     "legendFormat": "Unsuccessful"
    }
   ]
  },
  { "title": "IBM RBA - Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "# RBA Component Availability\n\nThe SLO target for availability for all components is 95%\n\nThe dashboard time-picker will control time-based charts but be aware that the \"SLI Period\" picker top-left will determine the SLI lookback period. Example - If you have set the SLI Period to 7 days, time-based charts will be calculating the SLI period on a rolling 7 day basis. The dashboard time-picker will dictate the time period you observe the SLI performance not the SLI lookback period."
   }
  },
  {
   "title": "Compnent Availability Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(sli_rba_service_status_automation)",
     "legendFormat": "Service - Automation"
    },
    {
     "expr": "sum(sli_rba_service_status_database)",
     "legendFormat": "Service - Database"
    },
    {
     "expr": "sum(sli_rba_service_status_runbook)",
     "legendFormat": "Service - Runbook"
    },
    {
     "expr": "sum(sli_rba_api_status_actions)",
     "legendFormat": "API - Actions"
    },
    {
     "expr": "sum(sli_rba_api_status_statistics)",
     "legendFormat": "API - Statistics"
    },
    { "expr": "sum(sli_rba_api_status_status)", "legendFormat": "API - Status" },
    {
     "expr": "sum(sli_rba_api_status_runbooks)",
     "legendFormat": "API - Runbooks"
    },
    {
     "expr": "sum(sli_rba_connection_status_script)",
     "legendFormat": "Connection - Script"
    }
   ]
  },
  {
   "title": "$span_min - Service Availability - Runbook",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_service_status_runbook[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$span_min - Service Availability - Automation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_service_status_automation[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$span_min - Service Availability - Database",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_service_status_database[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_service_status_runbook[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "runbook_service"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_service_status_automation[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "automation_service"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_service_status_database[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "database_service"
    }
   ]
  },
  {
   "title": "$span_min - API Availability - Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_actions[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$span_min - API Availability - Statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_statistics[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$span_min - API Availability - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_status[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$span_min - API Availability - Runbooks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_runbooks[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Availability - Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_actions[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "API - Actions"
    }
   ]
  },
  {
   "title": "API Availability - Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_statistics[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "API - Statistics"
    }
   ]
  },
  {
   "title": "API Availability - Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_status[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "API - Status"
    }
   ]
  },
  {
   "title": "API Availability - Runbooks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_api_status_runbooks[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "API - Runbooks"
    }
   ]
  },
  {
   "title": "$span_min - Connection Availability - SCRIPT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 1, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_connection_status_script[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "{{connection}}"
    }
   ]
  },
  {
   "title": "Connection Availability - SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sli_rba_connection_status_script[${span_min}m:1m])) / ${span_min} * 100",
     "legendFormat": "{{connection}}"
    }
   ]
  },
  { "title": "IBM RBA - Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Action Status Breakdown - Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rba_action_run_cancelled_count{action_name=~\"${get_actions}\"})",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "sum(rba_action_run_failed_count{action_name=~\"${get_actions}\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rba_action_run_successful_count{action_name=~\"${get_actions}\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rba_action_run_unknown_count{action_name=~\"${get_actions}\"})",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(rba_action_run_unsuccessful_count{action_name=~\"${get_actions}\"})",
     "legendFormat": "Unsuccessful"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "description": "This is a count of production runbook executions and alert action runs",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "sum(delta(rba_action_run_total{action_name=~\"${get_actions}\"}))",
     "legendFormat": "Action Executions"
    }
   ]
  },
  {
   "title": "Executions by status",
   "type": "timeseries",
   "description": "This is a count of action executions by status",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 83 },
   "targets": [
    {
     "expr": "sum(delta(rba_action_run_cancelled_count{action_name=~\"${get_actions}\"}))",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "sum(delta(rba_action_run_failed_count{action_name=~\"${get_actions}\"}))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(delta(rba_action_run_successful_count{action_name=~\"${get_actions}\"}))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(delta(rba_action_run_unknown_count{action_name=~\"${get_actions}\"}))",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(delta(rba_action_run_unsuccessful_count{action_name=~\"${get_actions}\"}))",
     "legendFormat": "Unsuccessful"
    }
   ]
  },
  {
   "title": "Average Action Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
   "targets": [
    { "expr": "avg(rba_action_execution_time)", "legendFormat": "Average execution time" },
    {
     "expr": "rba_action_execution_time{action_name=~\"${get_actions}\"}",
     "legendFormat": "{{action_name}}"
    }
   ]
  },
  { "title": "IBM RBA - Burn Rate Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 91 },
   "options": {
    "content": "# IBM RBA - Burn Rate Consumption\n\nAvailability SLO Target - 95%"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "options": {
    "content": "### Availability Burn Rate Windows\n\n<p>5% Error Budget over 7 days - 504 minutes\n<p>Fast Burn - 2% over Long Window - 1 hour, 2% over Short Window - 20 minutes\n<p>Burn Rate Calculation - 2% (10 minutes unavailability) over 1 hour:<br>\n.02 x (7*24*60) / Long Window (1 hour) = 3.36\n<p>Alerting Threshold - Burn Rate X SLO:\n<br>3.36 * 0.05 = 0.168\n\n<br>Fire Conditions - Burn Rate(1hr) and Burn Rate(20m) > 0.168\n<br>Clear Conditions - Burn Rate(1hr) and Burn Rate(20m) > 0.168"
   }
  },
  {
   "title": "Availability - Burn Rate Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "vector(3.36*0.05)",
     "legendFormat": "Service - Fast Burn Rate Threshold"
    },
    {
     "expr": "slo_rba_service_status_automation1hbasic",
     "legendFormat": "Service - Automation - 1hr Burn Rate"
    },
    {
     "expr": "slo_rba_service_status_automation20mbasic",
     "legendFormat": "Service - Automation - 20min Burn Rate"
    },
    {
     "expr": "ALERTS{alertname=\"RBA_SLO_FastBurnSimple\"}",
     "legendFormat": "Alert Duration"
    }
   ]
  }
 ]
}